project:
  type: default
  output-dir: docs
  pre-render: pre-render.py

format:
  live-html:
    toc: true
    toc-depth: 2
    toc-location: left
    code-fold: true
    code-tools: true
    code-overflow: wrap
    embed-resources: false
    theme: cosmo
    fig-width: 8
    fig-height: 4
    smooth-scroll: true

pyodide:
  engine-url: "./pyodide/"
  packages:
    - numpy
    - scipy
    - matplotlib
  resources:
    - sonar
  autorun: true
  show-startup-message: true
  cell-options:
    echo: false
    edit: false
